version: "2.3"

services:
  archdevclient:
    image: etacalpha/archdev:client
    ports:
      - 80:80
    restart: unless-stopped

  archdevserver:
    image: etacalpha/archdev:server
    ports:
      - 8080:8080
    restart: unless-stopped
